#!/bin/sh

/usr/sbin/ovsdb-server /var/lib/openvswitch/conf.db \
                     -vconsole:emer -vsyslog:err -vfile:info \
                     --remote=punix:/var/run/openvswitch/db.sock \
                     --private-key=db:Open_vSwitch,SSL,private_key \
                     --certificate=db:Open_vSwitch,SSL,certificate \
                     --bootstrap-ca-cert=db:Open_vSwitch,SSL,ca_cert \
                     --no-chdir --log-file=/var/log/openvswitch/ovsdb-server.log \
                     --pidfile=/var/run/openvswitch/ovsdb-server.pid \
                     --detach

/usr/sbin/ovs-vswitchd unix:/var/run/openvswitch/db.sock \
                      -vconsole:emer -vsyslog:err -vfile:info --mlockall --no-chdir \
                      --log-file=/var/log/openvswitch/ovs-vswitchd.log \
                      --pidfile=/var/run/openvswitch/ovs-vswitchd.pid \
                      --detach

/usr/bin/ovn-controller unix:/var/run/openvswitch/db.sock \
               -vconsole:emer -vsyslog:err -vfile:info --no-chdir \
               --log-file=/var/log/openvswitch/ovn-controller.log \
               --pidfile=/var/run/openvswitch/ovn-controller.pid \
               --monitor
